export const data = [
  {
    id: "101",
    date: "2022-03-25",
    trail: "Trail1",
    operator: "operator101",
    laborHours: 4,
    equiment1: "equipment1",
    equiment2: "equipment2",
    equiment3: "equipment3",
    equiment4: "equipment4",
    subTotal: 10,
    total: 20,
    selected: false,
  },
  {
    id: "102",
    date: "2022-03-25",
    trail: "Trail2",
    operator: "operator102",
    laborHours: 8,
    equiment1: "equipment1",
    equiment2: "equipment2",
    equiment3: "equipment3",
    equiment4: "equipment4",
    subTotal: 20,
    total: 40,
    selected: false,
  },
  {
    id: "103",
    date: "2022-03-25",
    trail: "Trail3",
    operator: "operator103",
    laborHours: 12,
    equiment1: "equipment1",
    equiment2: "equipment2",
    equiment3: "equipment3",
    equiment4: "equipment4",
    subTotal: 60,
    total: 120,
    selected: false,
  },
];

export const columns = [
  {
    name: "id",
    sortName: "id",
    label: "ID",
    align: "left",
    minWidth: 80,
    isDisableSorting: false,
  },
  {
    name: "fundStatus",
    sortName: "fundStatus",
    label: "Fund Status",
    align: "left",
    minWidth: 115,
    isDisableSorting: true,
  },
  {
    name: "date",
    sortName: "date",
    label: "Date",
    align: "left",
    minWidth: 115,
    isDisableSorting: true,
  },
  {
    name: "trail",
    sortName: "trail",
    label: "Trail",
    align: "left",
    isDisableSorting: true,
  },
  {
    name: "operator",
    sortName: "operator",
    label: "Operator",
    align: "left",
    minWidth: 100,
    isDisableSorting: true,
  },
  {
    name: "laborHours",
    sortName: "laborHours",
    label: "Labour Hours",
    align: "center",
    minWidth: 160,
    isDisableSorting: true,
  },
  {
    name: "equiment1",
    sortName: "equiment1",
    label: "Equipment #1",
    align: "left",
    minWidth: 170,
    isDisableSorting: true,
  },
  {
    name: "equiment2",
    sortName: "equiment2",
    label: "Equipment #2",
    align: "left",
    minWidth: 170,
    isDisableSorting: true,
  },
  {
    name: "equiment3",
    sortName: "equiment3",
    label: "Equipment #3",
    align: "left",
    minWidth: 170,
    isDisableSorting: true,
  },
  {
    name: "equiment4",
    sortName: "equiment4",
    label: "Equipment #4",
    align: "left",
    minWidth: 170,
    isDisableSorting: true,
  },
  {
    name: "subTotal",
    sortName: "subTotal",
    label: "Sub Total",
    align: "center",
    minWidth: 130,
    isDisableSorting: true,
  },
  {
    name: "total",
    sortName: "total",
    label: "Total",
    align: "center",
    minWidth: 100,
    isDisableSorting: true,
  },
];
